# Generated by Django 2.1.2 on 2018-10-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrecord',
            name='server',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='server',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='server',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='server',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='server',
        ),
        migrations.RemoveField(
            model_name='server',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
        migrations.DeleteModel(
            name='AssetRecord',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
