# Generated by Django 2.1.2 on 2018-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181024_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(max_length=128, verbose_name='磁盘型号'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=1, related_name='disk_list', to='api.Server', verbose_name='服务器'),
        ),
    ]
